owner: cawkz
repo: status

sites:
  - name: CawKZ Website
    url: https://cawkz.com
  - name: KZGO
    url: https://kzgo.eu

status-website:
  cname: status.cawkz.net
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg

  name: CawKZ Status
  theme: night

  robotsText: "User-agent: * \n Disallow: /"
