name: Response Time CI
on:
  schedule:
    - cron: "0 23 * * *"
  repository_dispatch:
    types: [response_time]
  workflow_dispatch:

jobs:
  release:
    name: Check status
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}

      - name: Update response time
        uses: upptime/uptime-monitor@v1.26.4
        with:
          command: "response-time"
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
