name: Uptime CI
on:
  schedule:
    - cron: "*/5 * * * *"
  repository_dispatch:
    types: [uptime]
  workflow_dispatch:

jobs:
  release:
    name: Check status
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}

      - name: Check endpoint status
        uses: upptime/uptime-monitor@v1.26.4
        with:
          command: "update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
